version: '3.6'

services:

  userme-demo-ui:
    build: .
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      - 3000:80
    environment:
      - DEMO_API_URL=http://localhost:2000
      - USERME_API_URL=http://localhost:7000
